dev.atguigu.url=jdbc:mysql://localhost:3306/atguigu
dev.atguigu.driver=com.mysql.cj.jdbc.Driver
dev.atguigu.username=root
dev.atguigu.password=root
test.atguigu.jdbc.url=jdbc:mysql://localhost:3306/atguigu
test.atguigu.jdbc.driver=com.mysql.cj.jdbc.Driver
test.atguigu.jdbc.username=zhangsan
test.atguigu.jdbc.password=123456
formal.atguigu.jdbc.url=jdbc:mysql://localhost:3306/atguigu
formal.atguigu.jdbc.driver=com.mysql.cj.jdbc.Driver
formal.atguigu.jdbc.username=lisi
formal.atguigu.jdbc.password=654321